#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 scale_fill_gradient2
#' @importFrom ggplot2 scale_x_reverse
#' @importFrom ggplot2 theme_bw
#' @importFrom glmmTMB bell
#' @importFrom glmmTMB beta_family
#' @importFrom glmmTMB betabinomial
#' @importFrom glmmTMB compois
#' @importFrom glmmTMB genpois
#' @importFrom glmmTMB glmmTMB
#' @importFrom glmmTMB lognormal
#' @importFrom glmmTMB nbinom1
#' @importFrom glmmTMB nbinom12
#' @importFrom glmmTMB nbinom2
#' @importFrom glmmTMB ordbeta
#' @importFrom glmmTMB skewnormal
#' @importFrom glmmTMB t_family
#' @importFrom glmmTMB truncated_compois
#' @importFrom glmmTMB truncated_genpois
#' @importFrom glmmTMB truncated_nbinom1
#' @importFrom glmmTMB truncated_nbinom2
#' @importFrom glmmTMB truncated_poisson
#' @importFrom glmmTMB tweedie
#' @importFrom glmmTMB ziGamma
#' @importFrom performance performance_aic
#' @importFrom performance r2
#' @importFrom performance r2_nakagawa
#' @importFrom Rdpack reprompt
#' @importFrom shiny runApp
#' @importFrom stats as.formula
#' @importFrom stats binomial
#' @importFrom stats Gamma
#' @importFrom stats gaussian
#' @importFrom stats glm
#' @importFrom stats inverse.gaussian
#' @importFrom stats p.adjust
#' @importFrom stats poisson
#' @importFrom stats quasi
#' @importFrom stats quasibinomial
#' @importFrom stats quasipoisson
#' @importFrom stats var
## usethis namespace: end
NULL
